"""Add is_active to ProductVariation

Revision ID: 31d8ffd3c258
Revises: a8cc9e40a4f6
Create Date: 2026-07-25 19:11:41.679776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d8ffd3c258'
down_revision: Union[str, Sequence[str], None] = 'a8cc9e40a4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variations', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variations', 'is_active')
    # ### end Alembic commands ###
