"""Add includes_rolls and notes

Revision ID: 4615a5ddfd0d
Revises: f2f2d287bc5f
Create Date: 2026-07-23 20:46:14.704352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4615a5ddfd0d'
down_revision: Union[str, Sequence[str], None] = 'f2f2d287bc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('product_variations', sa.Column('includes_rolls', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variations', 'includes_rolls')
    op.drop_column('order_items', 'notes')
    # ### end Alembic commands ###
