"""Add is_active to options

Revision ID: 504fb88d17b7
Revises: 4615a5ddfd0d
Create Date: 2026-07-25 18:33:59.758936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504fb88d17b7'
down_revision: Union[str, Sequence[str], None] = '4615a5ddfd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'price')
    op.drop_column('options', 'allow_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('allow_quantity', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('options', sa.Column('price', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
