"""Add product details

Revision ID: 8f3910354df7
Revises: 3ebf15b1ad65
Create Date: 2026-07-23 19:52:06.531972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3910354df7'
down_revision: Union[str, Sequence[str], None] = '3ebf15b1ad65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variations', sa.Column('description', sa.String(), nullable=True))
    op.add_column('product_variations', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variations', 'image_url')
    op.drop_column('product_variations', 'description')
    # ### end Alembic commands ###
