"""Add category and option fields

Revision ID: 9b287b996abd
Revises: 8f3910354df7
Create Date: 2026-07-23 20:18:07.969604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b287b996abd'
down_revision: Union[str, Sequence[str], None] = '8f3910354df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('categories', sa.Column('allow_quantity', sa.Boolean(), nullable=True))
    op.alter_column('categories', 'product_type_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('options', sa.Column('emoji', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'emoji')
    op.alter_column('categories', 'product_type_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('categories', 'allow_quantity')
    op.drop_column('categories', 'is_active')
    # ### end Alembic commands ###
