"""Add description to Option

Revision ID: a8cc9e40a4f6
Revises: 504fb88d17b7
Create Date: 2026-07-25 19:01:39.989867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cc9e40a4f6'
down_revision: Union[str, Sequence[str], None] = '504fb88d17b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'description')
    # ### end Alembic commands ###
